#!/usr/bin/env -S sh -c 'docker build --rm -t kungfu.azurecr.io/mw-megatron-deepspeed-update:latest -f $0 .'
FROM kungfu.azurecr.io/mw-megatron-deepspeed:latest

# Update
ADD . /workspace/Megatron-DeepSpeed
WORKDIR /workspace/Megatron-DeepSpeed
